version: "3.8"
services:
  app:
    build: .
    image: vanilla-node-dashboard:latest
    container_name: vanilla-node-dashboard
    ports:
      - "8080:3045"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
